### PR TITLE
Addition of ACE wave pressure BC

### PR DESCRIPTION
**Pull request by ikalash**
This PR adds the wave pressure NBC needed by ACE to Albany.  The attached document describes the formulation and implementation of this BC.  I added an example that shows how to call the BC and runs to completion, but it is non-physical.  I am not sure how to test the BC on a physical example, and will need the help of @jennifer-frederick and/or @lxmota for this.  We can do this before or after the PR is merged in - that is up to you.  We may want to make a few modifications to the BC namely the following:
- Do we want to throw an error is hs == 0?  
- Currently one needs to specify the time values and wave height values as arrays in the input file.  It would be straightforward to change this to read in a .txt file, if that is preferred.

@lxmota it would be great if you could have a look at how I coded this when you review just as a sanity check for me, rather than just clicking approve.

[PressureNBC.pdf](https://github.com/SNLComputation/LCM/files/5211063/PressureNBC.pdf)

### CODE REVIEW

**Review by lxmota — APPROVED** [review]
- Great, it inherits from the standard Neumann BC, which has the moving BC code, so we get that for free, which is needed.
- Use snake_case instead of camelCase for variable names, the LCM convention. For future reference, let's not create more work here.
- Always use brackets even for single statement ifs or loops.
- Maybe change ACEPRESS to ACEPRESSURE for clarity.
- Use clang format to align mis-indented lines. An LCM default clang format configuration will be used when clang format is run within a copy of the forked LCM repo.
- For hs == 0.0 the default zero pressures are OK. No need to issue error because this case will be common.
- Gravity OK as input because then code is independent of units. I know that there are a lot of magic numbers on the thermal side, which is unfortunate. Too many fires to put out to address that now.
- The water height values for the test are off the scale: thousands and tens of thousands of kilometers.

**Comment by ikalash** [comment]
> * Use snake_case instead of camelCase for variable names, the LCM convention. For future reference, let's not create more work here.

I'm not familiar with snake_case vs. camelCase.  Maybe you could make the change once the PR is merged in?

> * Always use brackets even for single statement ifs or loops.

I thought I did that.  I'm guessing if it's not there somewhere, it was already like that.  Maybe you can make the change where you see it's needed.

> * Maybe change ACEPRESS to ACEPRESSURE for clarity.

Ok I'll do that.

> * Use clang format to align mis-indented lines. An LCM default clang format configuration will be used when clang format is run within a copy of the forked LCM repo.

Would you mind doing this?  You have the scripts to do it I think.

> * For hs == 0.0 the default zero pressures are OK. No need to issue error because this case will be common.

So, in this case (hs == 0), I coded m1 = 0 in my formulation (otherwise it would be undefined).  I think it makes sense - do you agree?  Please see my document for the definition of m1.

> * Gravity OK as input because then code is independent of units. I know that there are a lot of magic numbers on the thermal side, which is unfortunate. Too many fires to put out to address that now.

Ok I'll keep it.

> * The water height values for the test are off the scale: thousands and tens of thousands of kilometers.

Yeah I know, they were BC values for the original ThermoMechanicalCan problem.  I will need you guys' help to set up an appropriate example.  I'd probably vote to do this later since there seem to be more urgent fires to put out.

**Comment by ikalash** [comment]
@lxmota : I noticed when running tests in this branch that a few of the ACE tests are failing with this error: 

```
: Restart Index not set. Not reading solution from exodus (-1)
2: [GenericSTKMeshStruct] Processing field requirements...
2:  ALBANY_ABORT statement at /home/ikalash/ACE/Albany-LCM-master/src/disc/stk/Albany_GenericSTKMeshStruct.cpp +1328
2: Error! The following requirements were not found in the discretization list: 'cell_boundary_indicator', 'node_boundary_indicator'.
2: 
2: [algol:1738443] *** Process received signal ***
2: [algol:1738443] Signal: Aborted (6)
2: [algol:1738443] Signal code:  (-6)
2:  ALBANY_ABORT statement at /home/ikalash/ACE/Albany-LCM-master/src/disc/stk/Albany_GenericSTKMeshStruct.cpp +1328
2: Error! The following requirements were not found in the discretization list: 'cell_boundary_indicator', 'node_boundary_indicator'.
```
It appears it happens in master too.  Is this expected?  The problematic tests are: 
```
 4 - ACE_StandAloneThermal2D_2Blocks (Failed)
	  5 - ACE_StandAloneThermal2D_2Blocks_Explicit (Failed)
	  6 - ACE_StandAloneThermal2D_4Blocks (Failed)
	  7 - ACE_CuboidStandAloneThermal3D (Failed)
	  8 - ACE_CuboidThermoMechanical3D_ThermalOnly (Failed)
	 10 - ACE_CuboidSequentialThermoMechanical3D (Failed)
	 11 - ACE_CuboidSequentialThermoMechanical3D_vardt (Failed)
	 12 - ACE_StandAloneThermal2.5DSlice_unstab (Failed)
	 13 - ACE_StandAloneThermal2.5DSlice_unstab_Explicit (Failed)
	 14 - ACE_StandAloneThermal2.5DSlice_stab (Failed)
```

**Comment by lxmota** [comment]
Ah yes, they are missing keywords for those fields since now they are essentially mandatory for ACE thermal too.

Alejandro

**Comment by ikalash** [comment]
Hmmm, so we should fix the tests, or disable them, I think, so they are not failing when running ctest.

**Comment by lxmota** [comment]
I can fix them, but I can’t get to them until after 9/17.

Alejandro

**Comment by ikalash** [comment]
That's fine, thanks, Alejandro.  I'll merge my PR in since it is not the cause of the errors.  I think we can put a check-mark next to the pressure NBC for now, though it needs testing/verification still.

**Comment by lxmota** [comment]
Sounds good, thanks!

Yes, I know it needs verification. I’ll add that to the list!

Alejandro

**Comment by ikalash** [comment]
Thanks, Alejandro!

**Pull request merged**
